server.port=8380
server.servlet.context-path=/api

spring.datasource.url=jdbc:h2:mem:urldb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

com.url.jwt.header-name=Authorization
com.url.jwt.header-prefix=Bearer 
com.url.jwt.key=J1/OKkA1WJdlEaeBcVoghLdps7kCdBYZ1/mWE190CMAuWRcB3qqF0h7Gep4wUMz8tfjoCcBdNiQ0ss8NJH7lmQ==
com.url.jwt.access-timeout=90000

com.url.charecter=10